baseURL = "https://docs.fireflyzero.com/"
languageCode = "en-us"
title = "Firefly Zero docs"
theme = "hugo-book"
enableGitInfo = true

[params]
BookSection = "*"
BookRepo = 'https://github.com/firefly-zero/docs.fireflyzero.com'
BookCommitPath = 'commit'
BookEditPath = 'edit/main'
BookDateFormat = '2006-01-02'
BookSearch = true
BookTheme = 'auto'

[markup.goldmark.renderer]
unsafe = true
